"""
Incremental Obsidian vault exporter for Hime's RAG index.

The vault lives at ${HIME_PROJECT_ROOT}/obsidian-vault/ — a fixed path resolved
from paths.OBSIDIAN_VAULT_DIR. The user opens this folder once in Obsidian; Hime
extends it automatically after every index build.

Incremental strategy: reads existing chunk files' frontmatter to find already-
written paragraph_ids. Only new chunks are written. _series_index.md and
_index.md are always regenerated (they're small summaries).

On first run also writes .obsidian/graph.json with node colors by tag so
Graph View looks structured out of the box.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

from ..core import paths as _paths


# ── helpers ──────────────────────────────────────────────────────────────────

def _chunk_filename(idx: int) -> str:
    return f"Chunk_{idx:04d}.md"


def _chunk_link(idx: int) -> str:
    return f"[[{_chunk_filename(idx)[:-3]}]]"


def _read_existing_paragraph_ids(series_dir: Path) -> set[int]:
    """Scan existing Chunk_*.md files and collect their paragraph_id values."""
    ids: set[int] = set()
    for f in series_dir.glob("Chunk_*.md"):
        text = f.read_text(encoding="utf-8")
        m = re.search(r"^paragraph_id:\s*(\d+)", text, re.MULTILINE)
        if m:
            ids.add(int(m.group(1)))
    return ids


def _write_chunk_file(path: Path, chunk: dict, total: int) -> None:
    idx = chunk["chunk_index"]
    prev_link = _chunk_link(idx - 1) if idx > 0 else "*(start)*"
    next_link = _chunk_link(idx + 1) if idx < total - 1 else "*(end)*"

    content = (
        "---\n"
        f"tags: [hime, series-{chunk['series_id']}, book-{chunk['book_id']}, "
        f"chapter-{chunk['chapter_id']}, translation]\n"
        f"series_id: {chunk['series_id']}\n"
        f"book_id: {chunk['book_id']}\n"
        f"chapter_id: {chunk['chapter_id']}\n"
        f"paragraph_id: {chunk['paragraph_id']}\n"
        f"chunk_index: {idx}\n"
        "---\n\n"
        "## 🇯🇵 Source\n\n"
        f"> {chunk['source_text']}\n\n"
        "## 🇬🇧 Translation\n\n"
        f"> {chunk['translated_text']}\n\n"
        "---\n\n"
        f"{prev_link} · [[_series_index]] · {next_link}\n"
    )
    path.write_text(content, encoding="utf-8")


def _write_series_index(path: Path, series_id: int, chunks: list[dict], last_update: str | None) -> None:
    updated = last_update or datetime.now().strftime("%Y-%m-%d")
    by_chapter: dict[int, list[dict]] = {}
    for c in chunks:
        by_chapter.setdefault(c["chapter_id"], []).append(c)

    chapter_lines = [
        f"- Chapter {ch_id} → {_chunk_link(ch_chunks[0]['chunk_index'])} ({len(ch_chunks)} chunks)"
        for ch_id, ch_chunks in sorted(by_chapter.items())
    ]
    all_links = " · ".join(_chunk_link(c["chunk_index"]) for c in chunks)

    content = (
        "---\n"
        f"tags: [hime, series-index, series-{series_id}]\n"
        f"series_id: {series_id}\n"
        "---\n\n"
        f"# Series {series_id} — Translation Memory\n\n"
        f"> [!info] Stats\n"
        f"> **Chunks:** {len(chunks)} | **Last updated:** {updated}\n\n"
        "## Chapters\n\n"
        + "\n".join(chapter_lines)
        + "\n\n## All Chunks\n\n"
        + all_links + "\n"
    )
    path.write_text(content, encoding="utf-8")


def _write_top_index(vault_dir: Path) -> None:
    hime_dir = vault_dir
    series_entries = []
    for d in sorted(hime_dir.iterdir()):
        if d.is_dir() and d.name.startswith("series_"):
            try:
                sid = int(d.name.split("_", 1)[1])
                count = len(list(d.glob("Chunk_*.md")))
                series_entries.append((sid, count))
            except ValueError:
                continue

    lines = [
        "---\ntags: [hime, index]\n---\n\n",
        "# Hime Translation Memory\n\n",
        "> [!tip] Auto-generated by Hime. Open this folder as an Obsidian vault.\n",
        "> Switch to **Graph View** to explore translation memory across series.\n\n",
        "## Series\n\n",
    ]
    for sid, count in series_entries:
        lines.append(f"- [[series_{sid}/_series_index|Series {sid}]] — {count} chunks\n")
    (hime_dir / "_index.md").write_text("".join(lines), encoding="utf-8")


# Series colors for graph.json — cycles through a palette
_PALETTE = [
    "#7c3aed", "#0ea5e9", "#10b981", "#f59e0b",
    "#ef4444", "#ec4899", "#8b5cf6", "#06b6d4",
]


def _bootstrap_obsidian_config(vault_dir: Path, known_series_ids: list[int]) -> None:
    """Write .obsidian/graph.json on first run (if it doesn't exist)."""
    obsidian_dir = vault_dir / ".obsidian"
    graph_path = obsidian_dir / "graph.json"
    if graph_path.exists():
        return  # Don't overwrite user customizations

    obsidian_dir.mkdir(parents=True, exist_ok=True)

    groups = [{"query": "tag:#hime", "color": {"a": 1, "rgb": int("e2e8f0", 16)}}]
    for i, sid in enumerate(sorted(known_series_ids)):
        color_hex = _PALETTE[i % len(_PALETTE)].lstrip("#")
        groups.append({
            "query": f"tag:#series-{sid}",
            "color": {"a": 1, "rgb": int(color_hex, 16)},
        })

    graph_config = {
        "collapse-filter": False,
        "search": "",
        "showTags": True,
        "showAttachments": False,
        "hideUnresolved": False,
        "showOrphans": True,
        "collapse-color-groups": False,
        "colorGroups": groups,
        "collapse-display": False,
        "showArrow": False,
        "textFadeMultiplier": 0,
        "nodeSizeMultiplier": 1.2,
        "lineSizeMultiplier": 1,
        "scale": 1,
        "close": False,
    }
    graph_path.write_text(json.dumps(graph_config, indent=2), encoding="utf-8")


# ── public API ────────────────────────────────────────────────────────────────

def sync_series(
    series_id: int,
    rag_dir: Path | None = None,
    vault_dir: Path | None = None,
) -> dict:
    """
    Incrementally sync a series RAG index into the Obsidian vault.
    Only writes chunk files that don't already exist (by paragraph_id).
    Always regenerates _series_index.md and _index.md.
    """
    from .store import SeriesStore

    rag_dir = rag_dir or _paths.RAG_DIR
    vault_dir = vault_dir or _paths.OBSIDIAN_VAULT_DIR

    db_path = rag_dir / f"series_{series_id}.db"
    if not db_path.exists():
        return {"series_id": series_id, "new_files": 0, "error": "db not found"}

    store = SeriesStore(db_path)
    try:
        chunks = store.all_chunks()
        stats = store.stats()
    finally:
        store.close()

    if not chunks:
        return {"series_id": series_id, "new_files": 0, "error": "no chunks"}

    for c in chunks:
        c["series_id"] = series_id

    series_dir = vault_dir / f"series_{series_id}"
    series_dir.mkdir(parents=True, exist_ok=True)

    existing_pids = _read_existing_paragraph_ids(series_dir)
    new_files = 0
    for chunk in chunks:
        if chunk["paragraph_id"] in existing_pids:
            continue
        out = series_dir / _chunk_filename(chunk["chunk_index"])
        _write_chunk_file(out, chunk, len(chunks))
        new_files += 1

    # Always regenerate summary files
    _write_series_index(
        series_dir / "_series_index.md",
        series_id=series_id,
        chunks=chunks,
        last_update=stats.get("last_update"),
    )
    _write_top_index(vault_dir)

    # Bootstrap .obsidian/graph.json on first run
    known_series = [
        int(d.name.split("_", 1)[1])
        for d in (vault_dir).iterdir()
        if d.is_dir() and d.name.startswith("series_")
        and d.name.split("_", 1)[1].isdigit()
    ]
    _bootstrap_obsidian_config(vault_dir, known_series)

    return {
        "series_id": series_id,
        "new_files": new_files,
        "total_chunks": len(chunks),
        "vault_dir": str(vault_dir),
    }
